# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Agenda Management API
  description: Move your app forward with the Uber API
  version: "1.0.0"
# the domain of the service
host: "https://mnv50ut6lj.execute-api.ap-northeast-1.amazonaws.com/staging"
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /agenda:
    get:
      summary: 一覧を取得
      description: |
        議題の一覧を取得
      parameters: []
      tags:
        - agendas
      responses:
        200:
          description: 議題の一覧を返す
          schema:
            type: "object"
            properties:
              content:
                type: "string"
                example: 
                    - agenda_id: 1-asvge34ewd4535g
                      title: 会議の進め方
                      detail: 会議の進行などを決める
                    - agenda_id: 1-vmiornvire3323c
                      title: 資金の使い道
                      detail: 資金の使い道を決める
                    - agenda_id: 1-dvkjf3kcnion32d
                      title:  卒研について
                      detail: 卒研の詳細
    post:
      tags:
      - "agendas"
      summary: "議題を登録"
      description: ""
      operationId: "registerAgenda"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            # Body schema with atomic property examples
            type: object
            properties:
                title:
                  type: string
                  example: "会議の進め方"
                detail:
                  type: string
                  example: '会議の進行などを決める'
      responses:
       200:
          description: "成功"
          schema:
            type: "object"
            properties:
              agenda_Id:
                type: "string"
                example: "1-asvge34ewd4535g"
                
  /agenda/{agenda_id}:
    get:
      summary: 取得
      description: 議題を取得
      parameters: [{
                    "name": "agenda_id",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }
            ]
      tags:
        - agenda
      responses:
        200:
          description: 議題を返す
          schema:
            type: "object"
            properties:
              agenda_id:
                type: string
                example: id
              title:
                type: string
                example: title
              detail:
                type: string
                example: detail
    put:
      tags:
      - "agenda"
      summary: "議題を更新"
      description: ""
      operationId: "putAgenda"
      parameters: [
                {
                "name": "agenda_id",
                "type": "string",
                "in": "path",
                "description": "議題ID",
                "required": true
                },
                {
                  "in": "body",
                  "name": "body",
                  "required": true,
                  "schema": {
                    "type": "object",
                    "properties": {
                        "title": {
                          "type": "string",
                          "example": "title"
                        },
                        "detail": {
                          "type": "string",
                          "example": 'detail'
                        }
                    }
                  }
                }
      ]
      responses:
       200:
          description: 議題内容を更新する
          schema:
            type: object
    delete:
      tags:
      - "agenda"
      summary: "議題を削除"
      description: ""
      operationId: "deleteAgenda"
      parameters: [
            {
                "name": "agenda_id",
                "type": "string",
                "in": "path",
                "description": "議題ID",
                "required": true
            }
            
      ]
      responses:
       200:
          description: 議題を削除
          schema:
            type: object
